"""Tests for TikZ/PGFPlots export agent and CLI integration."""

from __future__ import annotations

from unittest.mock import AsyncMock

import pytest

from paperbanana.agents.tikz_exporter import TikZExporterAgent
from paperbanana.core.types import DiagramType

# ---------------------------------------------------------------------------
# _extract_code
# ---------------------------------------------------------------------------


class TestExtractCode:
    def test_strips_latex_fence(self):
        raw = "```latex\n\\begin{tikzpicture}\n\\end{tikzpicture}\n```"
        assert TikZExporterAgent._extract_code(raw) == (
            "\\begin{tikzpicture}\n\\end{tikzpicture}"
        )

    def test_strips_tikz_fence(self):
        raw = "```tikz\n\\begin{tikzpicture}\n\\end{tikzpicture}\n```"
        assert "\\begin{tikzpicture}" in TikZExporterAgent._extract_code(raw)

    def test_strips_pgfplots_fence(self):
        raw = "```pgfplots\n\\begin{axis}\n\\end{axis}\n```"
        assert "\\begin{axis}" in TikZExporterAgent._extract_code(raw)

    def test_strips_generic_fence(self):
        raw = "```\n\\begin{tikzpicture}\n\\end{tikzpicture}\n```"
        assert "\\begin{tikzpicture}" in TikZExporterAgent._extract_code(raw)

    def test_raw_latex_passthrough(self):
        raw = "\\begin{tikzpicture}\n\\node {A};\n\\end{tikzpicture}"
        assert TikZExporterAgent._extract_code(raw) == raw

    def test_comment_prefix_passthrough(self):
        raw = "% PaperBanana\n\\begin{tikzpicture}\n\\end{tikzpicture}"
        assert TikZExporterAgent._extract_code(raw) == raw

    def test_bare_text_returned_stripped(self):
        raw = "  some unexpected output  "
        assert TikZExporterAgent._extract_code(raw) == "some unexpected output"

    def test_case_insensitive_fence(self):
        raw = "```LATEX\n\\begin{tikzpicture}\n\\end{tikzpicture}\n```"
        assert "\\begin{tikzpicture}" in TikZExporterAgent._extract_code(raw)


# ---------------------------------------------------------------------------
# TikZExporterAgent.run
# ---------------------------------------------------------------------------


@pytest.fixture()
def mock_vlm():
    vlm = AsyncMock()
    vlm.model_name = "gemini-2.0-flash"
    vlm.generate = AsyncMock(
        return_value="```latex\n\\begin{tikzpicture}\n\\node {Test};\n\\end{tikzpicture}\n```"
    )
    return vlm


@pytest.mark.asyncio
async def test_run_produces_tikz_with_header(mock_vlm, tmp_path):
    # Create a dummy image
    from PIL import Image

    img = Image.new("RGB", (100, 100), "white")
    img_path = tmp_path / "test.png"
    img.save(str(img_path))

    agent = TikZExporterAgent(mock_vlm, prompt_dir="prompts")
    result = await agent.run(
        image_path=str(img_path),
        source_context="Test methodology",
        caption="Test caption",
        diagram_type=DiagramType.METHODOLOGY,
        version="0.1.2",
        venue="neurips",
    )

    assert "% Generated by PaperBanana 0.1.2" in result
    assert "% Venue: neurips" in result
    assert "\\begin{tikzpicture}" in result
    assert "\\node {Test};" in result
    mock_vlm.generate.assert_called_once()


@pytest.mark.asyncio
async def test_run_uses_plot_prompt_for_statistical_plots(mock_vlm, tmp_path):
    from PIL import Image

    img = Image.new("RGB", (100, 100), "white")
    img_path = tmp_path / "plot.png"
    img.save(str(img_path))

    agent = TikZExporterAgent(mock_vlm, prompt_dir="prompts")
    result = await agent.run(
        image_path=str(img_path),
        source_context="Plot data",
        caption="Accuracy chart",
        diagram_type=DiagramType.STATISTICAL_PLOT,
    )

    assert "% Diagram type: statistical_plot" in result


@pytest.mark.asyncio
async def test_run_header_defaults(mock_vlm, tmp_path):
    from PIL import Image

    img = Image.new("RGB", (100, 100), "white")
    img_path = tmp_path / "test.png"
    img.save(str(img_path))

    agent = TikZExporterAgent(mock_vlm, prompt_dir="prompts")
    result = await agent.run(
        image_path=str(img_path),
        source_context="ctx",
        caption="cap",
    )

    # When no version/source_label provided, defaults to "unknown" / image_path
    assert "% Generated by PaperBanana unknown" in result
    assert str(img_path) in result


# ---------------------------------------------------------------------------
# Config settings
# ---------------------------------------------------------------------------


def test_export_tikz_setting_default():
    from paperbanana.core.config import Settings

    s = Settings()
    assert s.export_tikz is False
    assert s.export_pgfplots is False


def test_export_tikz_setting_override():
    from paperbanana.core.config import Settings

    s = Settings(export_tikz=True)
    assert s.export_tikz is True


# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------


def test_generation_output_tikz_path_default():
    from paperbanana.core.types import GenerationOutput

    out = GenerationOutput(image_path="test.png", description="desc")
    assert out.tikz_path is None


def test_generation_output_tikz_path_set():
    from paperbanana.core.types import GenerationOutput

    out = GenerationOutput(
        image_path="test.png", description="desc", tikz_path="test.tex"
    )
    assert out.tikz_path == "test.tex"


def test_progress_stages_exist():
    from paperbanana.core.types import PipelineProgressStage

    assert PipelineProgressStage.TIKZ_EXPORTER_START.value == "tikz_exporter_start"
    assert PipelineProgressStage.TIKZ_EXPORTER_END.value == "tikz_exporter_end"


# ---------------------------------------------------------------------------
# CLI: tikz subcommand
# ---------------------------------------------------------------------------


def test_tikz_command_missing_input():
    from typer.testing import CliRunner

    from paperbanana.cli import app

    runner = CliRunner()
    result = runner.invoke(app, ["tikz", "--input", "nonexistent.png"])
    assert result.exit_code == 1
    assert "not found" in result.output


def test_tikz_command_invalid_diagram_type(tmp_path):
    from PIL import Image
    from typer.testing import CliRunner

    from paperbanana.cli import app

    img = Image.new("RGB", (10, 10), "white")
    img_path = tmp_path / "test.png"
    img.save(str(img_path))

    runner = CliRunner()
    result = runner.invoke(
        app, ["tikz", "--input", str(img_path), "--diagram-type", "flowchart"]
    )
    assert result.exit_code == 1
    assert "diagram" in result.output or "plot" in result.output


def test_tikz_command_invalid_venue(tmp_path):
    from PIL import Image
    from typer.testing import CliRunner

    from paperbanana.cli import app

    img = Image.new("RGB", (10, 10), "white")
    img_path = tmp_path / "test.png"
    img.save(str(img_path))

    runner = CliRunner()
    result = runner.invoke(
        app, ["tikz", "--input", str(img_path), "--venue", "invalid"]
    )
    assert result.exit_code == 1
    assert "venue" in result.output.lower()
